refactor(jsonlayout): maintain layout even if data in logger context
tsedio/logger pull request #253
Opened 2024-07-10 16:56 UTC by Bugslive

## Informations

| Type                  |  Status                   | Migration |
| --------------- | ------------------ | ----------|
| Refactor            | Ready                    | No            |

---

## Description

- keep startTime, categoryName and level at the beginning of Json object when using Json Layout:
  _This makes it easier to track logs_

- minor fix in CONTRIBUTING.md

## Example

**Before:**

without additional data in logger context:
{"startTime":"2024-07-10T16:29:22.398Z","categoryName":"TSED","level":"INFO",..., "data":[]}

with additional data in logger context
`const context = new LogContext();
      context.set("user", "romain");`
{"user": romain", "startTime":"2024-07-10T16:29:22.398Z","categoryName":"TSED","level":"INFO",..., "data":[]}

**After:**

with additional data in logger context
{"startTime":"2024-07-10T16:29:22.398Z","categoryName":"TSED","level":"INFO", "user": romain", ..., "data":[]}

## Todos

- [X ] Tests
- [X] Coverage
- [X] Example
- [] Documentation

2024-08-26 13:44 UTC, Bugslive commented
Hello @Romakita. Do you think this request could be merged ? We would appreciate to have this minor evolution.

2024-08-26 14:45 UTC, Romakita approved these changes

2024-08-26 14:47 UTC, Romakita commented
Hello @Bugslive 
But changing the order assignment will allow data to override level, categoryName and startTime fields.

So I can't accept the change right know

2024-08-26 14:48 UTC, Romakita requested changes

2024-08-26 14:48 UTC, Romakita commented on packages/logger/src/common/layouts/utils/logEventToObject.ts
> +    ...loggingEvent.context.toJSON()
With this change, level, startTime, categoryName can be overridden :(

2024-08-27 14:55 UTC, Bugslive commented
Hello @Romakita.
I made an improvement to prevent startTime, level and categoryName to be overridden.
I also had a corresponding test.

2024-11-30 11:34 UTC, Romakita approved these changes

2025-05-06 05:01 UTC, closed without merging